###############################################################
#  Generated by:      Cadence Innovus 21.17-s075_1
#  OS:                Linux x86_64(Host ID centauri.esat.kuleuven.be)
#  Generated on:      Wed Apr 24 13:52:28 2024
#  Design:            sparc_exu_alu
#  Command:           create_ccopt_clock_tree_spec -views {AV_0100_wc_rc125_setup AV_0100_bc_rc0_hold } -file ../DesignDataIn/cts/ctsSpec_ccopt.tcl
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin rclk true

# Clocks present at pin rclk
#   RCLK (period 4.000ns) in timing_config 0100_mode([/users/micas/wjiang/WeijiePhd/Teaching/ALU_flow/DesignDataIn/dbs/place.enc.dat/mmmc/modes/0100_mode/0100_mode.sdc])
create_ccopt_clock_tree -name RCLK -source rclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner AV_0100_wc_rc125_setup_dc -early -clock_tree RCLK 0.040
set_ccopt_property target_max_trans_sdc -delay_corner AV_0100_wc_rc125_setup_dc -late -clock_tree RCLK 0.040
set_ccopt_property source_output_max_trans -delay_corner AV_0100_wc_rc125_setup_dc -early -clock_tree RCLK 0.200
set_ccopt_property source_output_max_trans -delay_corner AV_0100_bc_rc0_hold_dc -early -clock_tree RCLK 0.200
set_ccopt_property source_output_max_trans -delay_corner AV_0100_wc_rc125_setup_dc -late -clock_tree RCLK 0.200
set_ccopt_property source_output_max_trans -delay_corner AV_0100_bc_rc0_hold_dc -late -clock_tree RCLK 0.200
# Clock period setting for source pin of RCLK
set_ccopt_property clock_period -pin rclk 4

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:RCLK in timing_config:0100_mode (sdc /users/micas/wjiang/WeijiePhd/Teaching/ALU_flow/DesignDataIn/dbs/place.enc.dat/mmmc/modes/0100_mode/0100_mode.sdc)
create_ccopt_skew_group -name RCLK/0100_mode -sources rclk -auto_sinks
set_ccopt_property include_source_latency -skew_group RCLK/0100_mode true
set_ccopt_property extracted_from_clock_name -skew_group RCLK/0100_mode RCLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group RCLK/0100_mode 0100_mode
set_ccopt_property extracted_from_delay_corners -skew_group RCLK/0100_mode {AV_0100_wc_rc125_setup_dc AV_0100_bc_rc0_hold_dc}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

