

clean-pdk:
	rm -f assura  
	rm -f assura_tech.lib 
	rm -f cds.lib
	rm -f docs
	rm -f gpdk045 
	rm -f models
	rm -f pvs
	rm -f qrc
	rm -f pvtech
	rm -f pvtech.lib
	rm -f soce
	
clean-libs:
	rm -rf Digital_lib/
	rm -f libManager.log
	rm -rf .cadence
